#
#    The high-throughput toolkit (httk)
#    Copyright (C) 2012-2024 the httk AUTHORS
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Generated by 'httk registry gen property-records'. Do not edit directly; edit the definitions and regenerate.

"""Generated typed result records for the httk-core property definitions.

Each class stores one value of its property definition in typed columns; see
:mod:`httk.core.typed_records`. ``RECORD_KINDS`` maps each definition IRI to its class.
"""

import datetime
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Annotated, ClassVar

from httk.core import (
    IdentitySkip,
    Indexed,
    PropertyDefinition,
    RunEdge,
    StorageInfo,
    StrongLink,
    TypedRecord,
    TypedRecordSpec,
    Unique,
)
from httk.core.storage import StoredPropertyProjection

__all__ = [
    "RECORD_KINDS",
    "AtomicForceRecord",
    "EnthalpyRecord",
    "KineticEnergyRecord",
    "PotentialEnergyRecord",
    "PressureRecord",
    "StressTensorRecord",
    "TemperatureRecord",
    "VolumeRecord",
]


@dataclass(frozen=True)
class AtomicForceRecord(TypedRecord):
    """Atomic force as a typed record.

    The force on one atom (the negative gradient of the energy with respect to the position of the atom), in electronvolt per angstrom, as a vector over `dim_spatial` in the Cartesian frame of the structure it belongs to.
    This property is the base of force statistics: a statistic of it (such as an error or a bias over a population of atoms) has the same shape, one value per Cartesian component.
    A null value means the quantity is not available or not recorded.

    :param atomic_force: The atomic force value. Unit: angstrom^-1*eV.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_atomic_force",
        identity_name="core_atomic_force",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/atomic_force",
        "_httk_atomic_force",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    atomic_force: tuple[float, ...]
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class EnthalpyRecord(TypedRecord):
    """Enthalpy as a typed record.

    The enthalpy H = E_total + P V in electronvolt, with P the applied (external) pressure and V the cell volume. Extensive: refers to the whole simulated cell, not per atom.
    The reference/zero of the energy scale is method- and code-specific, so values are comparable only within one consistent computational setup.
    A null value means the quantity is not available or not recorded.

    :param enthalpy: The enthalpy value. Unit: eV.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_enthalpy",
        identity_name="core_enthalpy",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/enthalpy",
        "_httk_enthalpy",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    enthalpy: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class KineticEnergyRecord(TypedRecord):
    """Kinetic energy as a typed record.

    The nuclear kinetic energy of a system, in electronvolt. Extensive: refers to the whole simulated cell, not per atom.
    A null value means the quantity is not available or not recorded.

    :param kinetic_energy: The kinetic energy value. Unit: eV.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_kinetic_energy",
        identity_name="core_kinetic_energy",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/kinetic_energy",
        "_httk_kinetic_energy",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    kinetic_energy: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class PotentialEnergyRecord(TypedRecord):
    """Potential energy as a typed record.

    The potential energy of a computed system from the energy model, in electronvolt. Extensive: refers to the whole simulated cell, not per atom.
    The reference/zero of the energy scale is method- and code-specific, so values are comparable only within one consistent computational setup.
    A null value means the quantity is not available or not recorded.

    :param potential_energy: The potential energy value. Unit: eV.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_potential_energy",
        identity_name="core_potential_energy",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/potential_energy",
        "_httk_potential_energy",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    potential_energy: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class PressureRecord(TypedRecord):
    """Pressure as a typed record.

    The pressure of a system, in gigapascal (GPa; 1 GPa = 10^9 Pa). Pressure is positive in compression; stress is tensile-positive. For a hydrostatic state P = -tr(sigma)/3.
    A null value means the quantity is not available or not recorded.

    :param pressure: The pressure value. Unit: GPa.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_pressure",
        identity_name="core_pressure",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/pressure",
        "_httk_pressure",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    pressure: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class StressTensorRecord(TypedRecord):
    """Stress tensor as a typed record.

    The stress tensor of a system in Voigt notation, in gigapascal (GPa). Pressure is positive in compression; stress is tensile-positive. Voigt order [xx, yy, zz, yz, xz, xy].
    A null value means the quantity is not available or not recorded.

    :param stress_tensor: The stress tensor value. Unit: GPa.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_stress_tensor",
        identity_name="core_stress_tensor",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/stress_tensor",
        "_httk_stress_tensor",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    stress_tensor: tuple[float, ...]
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class TemperatureRecord(TypedRecord):
    """Temperature as a typed record.

    The temperature of a system, in kelvin.
    A null value means the quantity is not available or not recorded.

    :param temperature: The temperature value. Unit: K.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_temperature",
        identity_name="core_temperature",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/temperature",
        "_httk_temperature",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    temperature: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


@dataclass(frozen=True)
class VolumeRecord(TypedRecord):
    """Volume as a typed record.

    The volume of the simulation cell, in cubic angstrom. Extensive: refers to the whole simulated cell, not per atom.
    A null value means the quantity is not available or not recorded.

    :param volume: The volume value. Unit: angstrom^3.
    :param product_of: The entries this value is a product of, as labeled edges.
    :param id: The human-readable entry id shared by all revisions; minted by the store when None.
    :param immutable_id: The per-revision immutable id; minted by the store when None.
    :param last_modified: The optional timezone-aware metadata timestamp.
    """

    __httk_storage__: ClassVar[StorageInfo] = StorageInfo(
        storage_name="core_volume",
        identity_name="core_volume",
    )
    __httk_typed_record__: ClassVar[TypedRecordSpec] = TypedRecordSpec(
        "https://schemas.httk.org/defs/v0.1/properties/core/volume",
        "_httk_volume",
    )
    __httk_property_definitions__: ClassVar[Mapping[str, PropertyDefinition]] = __httk_typed_record__.definitions()
    __httk_stored_properties__: ClassVar[Mapping[str, StoredPropertyProjection]] = __httk_typed_record__.projections()

    volume: float
    product_of: Annotated[tuple[RunEdge, ...], StrongLink("product_of", reverse="has_product", role="subject")] = ()
    id: Annotated[str | None, IdentitySkip(), Indexed()] = field(default=None, compare=False)
    immutable_id: Annotated[str | None, IdentitySkip(), Unique()] = field(default=None, compare=False)
    last_modified: Annotated[datetime.datetime | None, IdentitySkip()] = field(default=None, compare=False)


#: The generated record class of each property definition IRI.
RECORD_KINDS: Mapping[str, type[TypedRecord]] = MappingProxyType(
    {
        "https://schemas.httk.org/defs/v0.1/properties/core/atomic_force": AtomicForceRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/enthalpy": EnthalpyRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/kinetic_energy": KineticEnergyRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/potential_energy": PotentialEnergyRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/pressure": PressureRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/stress_tensor": StressTensorRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/temperature": TemperatureRecord,
        "https://schemas.httk.org/defs/v0.1/properties/core/volume": VolumeRecord,
    }
)
