"""Storage declarations, identity, and stored-property protocols."""

from .identity import (
    StorageProjectionCycleError,
    canonical_form,
    content_id,
    project_storage_record,
    register_canonical_encoder,
    resolve_storage_record,
    storage_identity_name,
)
from .markers import (
    STORAGE_INFO_ATTRIBUTE,
    DedupPolicy,
    IdentitySkip,
    Indexed,
    Related,
    RelationshipLink,
    Shape,
    Skip,
    StorageInfo,
    Unique,
    stored_property,
)
from .stored_properties import (
    STORED_PROPERTY_PROJECTIONS_ATTRIBUTE,
    QueryContext,
    QueryExpression,
    QueryField,
    QueryLiteralError,
    QueryScope,
    QueryValue,
    StoredPropertyProjection,
    StoredPropertyQuery,
    StoredPropertyResponse,
    StoredPropertySort,
    stored_property_projections,
)

__all__ = [
    "STORAGE_INFO_ATTRIBUTE",
    "STORED_PROPERTY_PROJECTIONS_ATTRIBUTE",
    "DedupPolicy",
    "IdentitySkip",
    "Indexed",
    "QueryContext",
    "QueryExpression",
    "QueryField",
    "QueryLiteralError",
    "QueryScope",
    "QueryValue",
    "Related",
    "RelationshipLink",
    "Shape",
    "Skip",
    "StorageInfo",
    "StorageProjectionCycleError",
    "StoredPropertyProjection",
    "StoredPropertyQuery",
    "StoredPropertyResponse",
    "StoredPropertySort",
    "Unique",
    "canonical_form",
    "content_id",
    "project_storage_record",
    "register_canonical_encoder",
    "resolve_storage_record",
    "storage_identity_name",
    "stored_property",
    "stored_property_projections",
]
